name: Metta Investments
favicon: null
layout_spectrum: 0.38760473346337676
typography_spectrum: 0.5467281215824187
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b8b8b8'
    - '#7d7d7d'
    - '#616161'
    - '#2c2c2c'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
